[versions]
compileSdk = "35"
minSdk = "24"
targetSdk = "35"
androidx-core-ktx = "1.13.1"
androidx-appcompat = "1.6.1"
material = "1.10.0"
androidx-constraintlayout = "2.1.4"
junit = "4.13.2"
androidx-junit = "1.1.5"
androidx-espresso-core = "3.5.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }

[plugins]
android-application = { id = "com.android.application", version = "8.2.0" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.9.0" }
